// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package db

import (
	"context"
	"database/sql"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, name, description, status, workspace_path, agent_dir_path, model, mention_patterns, soul_md, agents_md, identity_md, user_md, tools_md, heartbeat_md, memory_md)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, status, workspace_path, agent_dir_path, model, mention_patterns, soul_md, agents_md, identity_md, user_md, tools_md, heartbeat_md, memory_md, active_session_key, current_task_id, created_at, updated_at
`

type CreateAgentParams struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	Status          sql.NullString `json:"status"`
	WorkspacePath   sql.NullString `json:"workspace_path"`
	AgentDirPath    sql.NullString `json:"agent_dir_path"`
	Model           sql.NullString `json:"model"`
	MentionPatterns sql.NullString `json:"mention_patterns"`
	SoulMd          sql.NullString `json:"soul_md"`
	AgentsMd        sql.NullString `json:"agents_md"`
	IdentityMd      sql.NullString `json:"identity_md"`
	UserMd          sql.NullString `json:"user_md"`
	ToolsMd         sql.NullString `json:"tools_md"`
	HeartbeatMd     sql.NullString `json:"heartbeat_md"`
	MemoryMd        sql.NullString `json:"memory_md"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.WorkspacePath,
		arg.AgentDirPath,
		arg.Model,
		arg.MentionPatterns,
		arg.SoulMd,
		arg.AgentsMd,
		arg.IdentityMd,
		arg.UserMd,
		arg.ToolsMd,
		arg.HeartbeatMd,
		arg.MemoryMd,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.WorkspacePath,
		&i.AgentDirPath,
		&i.Model,
		&i.MentionPatterns,
		&i.SoulMd,
		&i.AgentsMd,
		&i.IdentityMd,
		&i.UserMd,
		&i.ToolsMd,
		&i.HeartbeatMd,
		&i.MemoryMd,
		&i.ActiveSessionKey,
		&i.CurrentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = ?
`

func (q *Queries) DeleteAgent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAgent, id)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, description, status, workspace_path, agent_dir_path, model, mention_patterns, soul_md, agents_md, identity_md, user_md, tools_md, heartbeat_md, memory_md, active_session_key, current_task_id, created_at, updated_at FROM agents WHERE id = ? LIMIT 1
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.WorkspacePath,
		&i.AgentDirPath,
		&i.Model,
		&i.MentionPatterns,
		&i.SoulMd,
		&i.AgentsMd,
		&i.IdentityMd,
		&i.UserMd,
		&i.ToolsMd,
		&i.HeartbeatMd,
		&i.MemoryMd,
		&i.ActiveSessionKey,
		&i.CurrentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, description, status, workspace_path, agent_dir_path, model, mention_patterns, soul_md, agents_md, identity_md, user_md, tools_md, heartbeat_md, memory_md, active_session_key, current_task_id, created_at, updated_at FROM agents ORDER BY created_at DESC
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.WorkspacePath,
			&i.AgentDirPath,
			&i.Model,
			&i.MentionPatterns,
			&i.SoulMd,
			&i.AgentsMd,
			&i.IdentityMd,
			&i.UserMd,
			&i.ToolsMd,
			&i.HeartbeatMd,
			&i.MemoryMd,
			&i.ActiveSessionKey,
			&i.CurrentTaskID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents SET 
    name = ?, description = ?, status = ?, model = ?, mention_patterns = ?,
    soul_md = ?, agents_md = ?, identity_md = ?, user_md = ?, tools_md = ?, heartbeat_md = ?,
    active_session_key = ?, current_task_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? RETURNING id, name, description, status, workspace_path, agent_dir_path, model, mention_patterns, soul_md, agents_md, identity_md, user_md, tools_md, heartbeat_md, memory_md, active_session_key, current_task_id, created_at, updated_at
`

type UpdateAgentParams struct {
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	Status           sql.NullString `json:"status"`
	Model            sql.NullString `json:"model"`
	MentionPatterns  sql.NullString `json:"mention_patterns"`
	SoulMd           sql.NullString `json:"soul_md"`
	AgentsMd         sql.NullString `json:"agents_md"`
	IdentityMd       sql.NullString `json:"identity_md"`
	UserMd           sql.NullString `json:"user_md"`
	ToolsMd          sql.NullString `json:"tools_md"`
	HeartbeatMd      sql.NullString `json:"heartbeat_md"`
	ActiveSessionKey sql.NullString `json:"active_session_key"`
	CurrentTaskID    sql.NullString `json:"current_task_id"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, updateAgent,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Model,
		arg.MentionPatterns,
		arg.SoulMd,
		arg.AgentsMd,
		arg.IdentityMd,
		arg.UserMd,
		arg.ToolsMd,
		arg.HeartbeatMd,
		arg.ActiveSessionKey,
		arg.CurrentTaskID,
		arg.ID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.WorkspacePath,
		&i.AgentDirPath,
		&i.Model,
		&i.MentionPatterns,
		&i.SoulMd,
		&i.AgentsMd,
		&i.IdentityMd,
		&i.UserMd,
		&i.ToolsMd,
		&i.HeartbeatMd,
		&i.MemoryMd,
		&i.ActiveSessionKey,
		&i.CurrentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentStatus = `-- name: UpdateAgentStatus :exec
UPDATE agents SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateAgentStatusParams struct {
	Status sql.NullString `json:"status"`
	ID     string         `json:"id"`
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentStatus, arg.Status, arg.ID)
	return err
}
