// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package db

import (
	"context"
	"database/sql"
)

const createChatMessage = `-- name: CreateChatMessage :one

INSERT INTO chat_messages (id, session_id, role, content)
VALUES (?, ?, ?, ?)
RETURNING id, session_id, role, content, created_at
`

type CreateChatMessageParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Role      string `json:"role"`
	Content   string `json:"content"`
}

// ============ Chat Messages ============
func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, createChatMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.Content,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createChatSession = `-- name: CreateChatSession :one

INSERT INTO chat_sessions (id, agent_id, openclaw_session_key, status)
VALUES (?, ?, ?, ?)
RETURNING id, agent_id, openclaw_session_key, status, started_at, ended_at, message_count
`

type CreateChatSessionParams struct {
	ID                 string         `json:"id"`
	AgentID            string         `json:"agent_id"`
	OpenclawSessionKey sql.NullString `json:"openclaw_session_key"`
	Status             string         `json:"status"`
}

// ============ Chat Sessions ============
func (q *Queries) CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, createChatSession,
		arg.ID,
		arg.AgentID,
		arg.OpenclawSessionKey,
		arg.Status,
	)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.OpenclawSessionKey,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.MessageCount,
	)
	return i, err
}

const endChatSession = `-- name: EndChatSession :exec
UPDATE chat_sessions 
SET status = 'ended', ended_at = CURRENT_TIMESTAMP 
WHERE id = ?
`

func (q *Queries) EndChatSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, endChatSession, id)
	return err
}

const getChatSession = `-- name: GetChatSession :one
SELECT id, agent_id, openclaw_session_key, status, started_at, ended_at, message_count FROM chat_sessions WHERE id = ? LIMIT 1
`

func (q *Queries) GetChatSession(ctx context.Context, id string) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, getChatSession, id)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.OpenclawSessionKey,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.MessageCount,
	)
	return i, err
}

const listChatSessionsByAgent = `-- name: ListChatSessionsByAgent :many
SELECT id, agent_id, openclaw_session_key, status, started_at, ended_at, message_count FROM chat_sessions 
WHERE agent_id = ? 
ORDER BY started_at DESC
`

func (q *Queries) ListChatSessionsByAgent(ctx context.Context, agentID string) ([]ChatSession, error) {
	rows, err := q.db.QueryContext(ctx, listChatSessionsByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatSession{}
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.OpenclawSessionKey,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySession = `-- name: ListMessagesBySession :many
SELECT id, session_id, role, content, created_at FROM chat_messages 
WHERE session_id = ? 
ORDER BY created_at ASC
`

func (q *Queries) ListMessagesBySession(ctx context.Context, sessionID string) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageCount = `-- name: UpdateMessageCount :exec
UPDATE chat_sessions 
SET message_count = message_count + 1 
WHERE id = ?
`

func (q *Queries) UpdateMessageCount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateMessageCount, id)
	return err
}
