// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (id, task_id, author, content)
VALUES (?, ?, ?, ?)
RETURNING id, task_id, author, content, created_at
`

type CreateCommentParams struct {
	ID      string `json:"id"`
	TaskID  string `json:"task_id"`
	Author  string `json:"author"`
	Content string `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.ID,
		arg.TaskID,
		arg.Author,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = ?
`

func (q *Queries) DeleteComment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, task_id, author, content, created_at FROM comments WHERE id = ? LIMIT 1
`

func (q *Queries) GetComment(ctx context.Context, id string) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listCommentsByTask = `-- name: ListCommentsByTask :many
SELECT id, task_id, author, content, created_at FROM comments WHERE task_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListCommentsByTask(ctx context.Context, taskID string) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Author,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
