// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
	"database/sql"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (id, task_id, agent_id, type, message, details)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, task_id, agent_id, type, message, details, created_at
`

type CreateEventParams struct {
	ID      string         `json:"id"`
	TaskID  sql.NullString `json:"task_id"`
	AgentID sql.NullString `json:"agent_id"`
	Type    string         `json:"type"`
	Message string         `json:"message"`
	Details sql.NullString `json:"details"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.ID,
		arg.TaskID,
		arg.AgentID,
		arg.Type,
		arg.Message,
		arg.Details,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AgentID,
		&i.Type,
		&i.Message,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, task_id, agent_id, type, message, details, created_at FROM events ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListEvents(ctx context.Context, limit int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AgentID,
			&i.Type,
			&i.Message,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByAgent = `-- name: ListEventsByAgent :many
SELECT id, task_id, agent_id, type, message, details, created_at FROM events WHERE agent_id = ? ORDER BY created_at DESC LIMIT ?
`

type ListEventsByAgentParams struct {
	AgentID sql.NullString `json:"agent_id"`
	Limit   int64          `json:"limit"`
}

func (q *Queries) ListEventsByAgent(ctx context.Context, arg ListEventsByAgentParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByAgent, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AgentID,
			&i.Type,
			&i.Message,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByTask = `-- name: ListEventsByTask :many
SELECT id, task_id, agent_id, type, message, details, created_at FROM events WHERE task_id = ? ORDER BY created_at DESC LIMIT ?
`

type ListEventsByTaskParams struct {
	TaskID sql.NullString `json:"task_id"`
	Limit  int64          `json:"limit"`
}

func (q *Queries) ListEventsByTask(ctx context.Context, arg ListEventsByTaskParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByTask, arg.TaskID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AgentID,
			&i.Type,
			&i.Message,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
