// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Agent struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	Status           sql.NullString `json:"status"`
	WorkspacePath    sql.NullString `json:"workspace_path"`
	AgentDirPath     sql.NullString `json:"agent_dir_path"`
	Model            sql.NullString `json:"model"`
	MentionPatterns  sql.NullString `json:"mention_patterns"`
	SoulMd           sql.NullString `json:"soul_md"`
	AgentsMd         sql.NullString `json:"agents_md"`
	IdentityMd       sql.NullString `json:"identity_md"`
	UserMd           sql.NullString `json:"user_md"`
	ToolsMd          sql.NullString `json:"tools_md"`
	HeartbeatMd      sql.NullString `json:"heartbeat_md"`
	MemoryMd         sql.NullString `json:"memory_md"`
	ActiveSessionKey sql.NullString `json:"active_session_key"`
	CurrentTaskID    sql.NullString `json:"current_task_id"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

type ChatMessage struct {
	ID        string       `json:"id"`
	SessionID string       `json:"session_id"`
	Role      string       `json:"role"`
	Content   string       `json:"content"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type ChatSession struct {
	ID                 string         `json:"id"`
	AgentID            string         `json:"agent_id"`
	OpenclawSessionKey sql.NullString `json:"openclaw_session_key"`
	Status             string         `json:"status"`
	StartedAt          sql.NullTime   `json:"started_at"`
	EndedAt            sql.NullTime   `json:"ended_at"`
	MessageCount       sql.NullInt64  `json:"message_count"`
}

type Comment struct {
	ID        string       `json:"id"`
	TaskID    string       `json:"task_id"`
	Author    string       `json:"author"`
	Content   string       `json:"content"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Event struct {
	ID        string         `json:"id"`
	TaskID    sql.NullString `json:"task_id"`
	AgentID   sql.NullString `json:"agent_id"`
	Type      string         `json:"type"`
	Message   string         `json:"message"`
	Details   sql.NullString `json:"details"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Phase struct {
	ID                 string         `json:"id"`
	TaskID             string         `json:"task_id"`
	Sequence           int64          `json:"sequence"`
	Title              string         `json:"title"`
	Description        sql.NullString `json:"description"`
	Status             sql.NullString `json:"status"`
	ContextMd          sql.NullString `json:"context_md"`
	ResearchMd         sql.NullString `json:"research_md"`
	PlanMd             sql.NullString `json:"plan_md"`
	SummaryMd          sql.NullString `json:"summary_md"`
	UatMd              sql.NullString `json:"uat_md"`
	VerificationResult sql.NullString `json:"verification_result"`
	SessionKey         sql.NullString `json:"session_key"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
}

type Project struct {
	ID                string         `json:"id"`
	Name              string         `json:"name"`
	Description       sql.NullString `json:"description"`
	Status            sql.NullString `json:"status"`
	Color             sql.NullString `json:"color"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	Location          sql.NullString `json:"location"`
	DefaultBranch     sql.NullString `json:"default_branch"`
	LocalExecBranch   sql.NullString `json:"local_exec_branch"`
	RemoteMergeBranch sql.NullString `json:"remote_merge_branch"`
}

type Setting struct {
	ID                      string         `json:"id"`
	OpenclawGatewayUrl      sql.NullString `json:"openclaw_gateway_url"`
	OpenclawGatewayToken    sql.NullString `json:"openclaw_gateway_token"`
	DefaultModel            sql.NullString `json:"default_model"`
	MaxParallelExecutions   sql.NullInt64  `json:"max_parallel_executions"`
	DefaultProjectDirectory sql.NullString `json:"default_project_directory"`
	GsdDepth                sql.NullString `json:"gsd_depth"`
	GsdMode                 sql.NullString `json:"gsd_mode"`
	GsdResearchEnabled      sql.NullInt64  `json:"gsd_research_enabled"`
	GsdPlanCheckEnabled     sql.NullInt64  `json:"gsd_plan_check_enabled"`
	GsdVerifierEnabled      sql.NullInt64  `json:"gsd_verifier_enabled"`
	RalphMaxIterations      sql.NullInt64  `json:"ralph_max_iterations"`
	RalphAutoCommit         sql.NullInt64  `json:"ralph_auto_commit"`
	Theme                   sql.NullString `json:"theme"`
	UpdatedAt               sql.NullTime   `json:"updated_at"`
}

type Story struct {
	ID                 string         `json:"id"`
	TaskID             string         `json:"task_id"`
	Sequence           int64          `json:"sequence"`
	Title              string         `json:"title"`
	Description        sql.NullString `json:"description"`
	Priority           sql.NullInt64  `json:"priority"`
	Passes             sql.NullBool   `json:"passes"`
	AcceptanceCriteria sql.NullString `json:"acceptance_criteria"`
	Iterations         sql.NullInt64  `json:"iterations"`
	LastError          sql.NullString `json:"last_error"`
	SessionKey         sql.NullString `json:"session_key"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
}

type SubAgent struct {
	ID             string         `json:"id"`
	OrchestratorID string         `json:"orchestrator_id"`
	TaskID         sql.NullString `json:"task_id"`
	Name           string         `json:"name"`
	Status         sql.NullString `json:"status"`
	SessionKey     sql.NullString `json:"session_key"`
	SessionLabel   sql.NullString `json:"session_label"`
	Purpose        sql.NullString `json:"purpose"`
	Iteration      sql.NullInt64  `json:"iteration"`
	Output         sql.NullString `json:"output"`
	Error          sql.NullString `json:"error"`
	SpawnedAt      sql.NullTime   `json:"spawned_at"`
	CompletedAt    sql.NullTime   `json:"completed_at"`
}

type Task struct {
	ID             string         `json:"id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	AgentID        sql.NullString `json:"agent_id"`
	ProjectID      sql.NullString `json:"project_id"`
	ParentTaskID   sql.NullString `json:"parent_task_id"`
	Status         sql.NullString `json:"status"`
	Priority       sql.NullInt64  `json:"priority"`
	GitBranch      sql.NullString `json:"git_branch"`
	ProjectMd      sql.NullString `json:"project_md"`
	RequirementsMd sql.NullString `json:"requirements_md"`
	RoadmapMd      sql.NullString `json:"roadmap_md"`
	StateMd        sql.NullString `json:"state_md"`
	PrdJson        sql.NullString `json:"prd_json"`
	ProgressTxt    sql.NullString `json:"progress_txt"`
	QualityChecks  sql.NullString `json:"quality_checks"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	StartedAt      sql.NullTime   `json:"started_at"`
	CompletedAt    sql.NullTime   `json:"completed_at"`
	DelegationMode sql.NullString `json:"delegation_mode"`
	RetryCount     int64          `json:"retry_count"`
	ScheduledAt    sql.NullTime   `json:"scheduled_at"`
	RetryAt        sql.NullTime   `json:"retry_at"`
}
