// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: phases.sql

package db

import (
	"context"
	"database/sql"
)

const createPhase = `-- name: CreatePhase :one
INSERT INTO phases (id, task_id, sequence, title, description, status)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, task_id, sequence, title, description, status, context_md, research_md, plan_md, summary_md, uat_md, verification_result, session_key, created_at, updated_at
`

type CreatePhaseParams struct {
	ID          string         `json:"id"`
	TaskID      string         `json:"task_id"`
	Sequence    int64          `json:"sequence"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      sql.NullString `json:"status"`
}

func (q *Queries) CreatePhase(ctx context.Context, arg CreatePhaseParams) (Phase, error) {
	row := q.db.QueryRowContext(ctx, createPhase,
		arg.ID,
		arg.TaskID,
		arg.Sequence,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	var i Phase
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Sequence,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ContextMd,
		&i.ResearchMd,
		&i.PlanMd,
		&i.SummaryMd,
		&i.UatMd,
		&i.VerificationResult,
		&i.SessionKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePhase = `-- name: DeletePhase :exec
DELETE FROM phases WHERE id = ?
`

func (q *Queries) DeletePhase(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePhase, id)
	return err
}

const getPhase = `-- name: GetPhase :one
SELECT id, task_id, sequence, title, description, status, context_md, research_md, plan_md, summary_md, uat_md, verification_result, session_key, created_at, updated_at FROM phases WHERE id = ? LIMIT 1
`

func (q *Queries) GetPhase(ctx context.Context, id string) (Phase, error) {
	row := q.db.QueryRowContext(ctx, getPhase, id)
	var i Phase
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Sequence,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ContextMd,
		&i.ResearchMd,
		&i.PlanMd,
		&i.SummaryMd,
		&i.UatMd,
		&i.VerificationResult,
		&i.SessionKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPhasesByTask = `-- name: ListPhasesByTask :many
SELECT id, task_id, sequence, title, description, status, context_md, research_md, plan_md, summary_md, uat_md, verification_result, session_key, created_at, updated_at FROM phases WHERE task_id = ? ORDER BY sequence ASC
`

func (q *Queries) ListPhasesByTask(ctx context.Context, taskID string) ([]Phase, error) {
	rows, err := q.db.QueryContext(ctx, listPhasesByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Phase{}
	for rows.Next() {
		var i Phase
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Sequence,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ContextMd,
			&i.ResearchMd,
			&i.PlanMd,
			&i.SummaryMd,
			&i.UatMd,
			&i.VerificationResult,
			&i.SessionKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePhase = `-- name: UpdatePhase :one
UPDATE phases SET
    title = ?, description = ?, status = ?,
    context_md = ?, research_md = ?, plan_md = ?, summary_md = ?, uat_md = ?,
    verification_result = ?, session_key = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? RETURNING id, task_id, sequence, title, description, status, context_md, research_md, plan_md, summary_md, uat_md, verification_result, session_key, created_at, updated_at
`

type UpdatePhaseParams struct {
	Title              string         `json:"title"`
	Description        sql.NullString `json:"description"`
	Status             sql.NullString `json:"status"`
	ContextMd          sql.NullString `json:"context_md"`
	ResearchMd         sql.NullString `json:"research_md"`
	PlanMd             sql.NullString `json:"plan_md"`
	SummaryMd          sql.NullString `json:"summary_md"`
	UatMd              sql.NullString `json:"uat_md"`
	VerificationResult sql.NullString `json:"verification_result"`
	SessionKey         sql.NullString `json:"session_key"`
	ID                 string         `json:"id"`
}

func (q *Queries) UpdatePhase(ctx context.Context, arg UpdatePhaseParams) (Phase, error) {
	row := q.db.QueryRowContext(ctx, updatePhase,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.ContextMd,
		arg.ResearchMd,
		arg.PlanMd,
		arg.SummaryMd,
		arg.UatMd,
		arg.VerificationResult,
		arg.SessionKey,
		arg.ID,
	)
	var i Phase
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Sequence,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ContextMd,
		&i.ResearchMd,
		&i.PlanMd,
		&i.SummaryMd,
		&i.UatMd,
		&i.VerificationResult,
		&i.SessionKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePhaseStatus = `-- name: UpdatePhaseStatus :exec
UPDATE phases SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdatePhaseStatusParams struct {
	Status sql.NullString `json:"status"`
	ID     string         `json:"id"`
}

func (q *Queries) UpdatePhaseStatus(ctx context.Context, arg UpdatePhaseStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePhaseStatus, arg.Status, arg.ID)
	return err
}
