// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, name, description, status, color, location, default_branch, local_exec_branch, remote_merge_branch)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, status, color, created_at, updated_at, location, default_branch, local_exec_branch, remote_merge_branch
`

type CreateProjectParams struct {
	ID                string         `json:"id"`
	Name              string         `json:"name"`
	Description       sql.NullString `json:"description"`
	Status            sql.NullString `json:"status"`
	Color             sql.NullString `json:"color"`
	Location          sql.NullString `json:"location"`
	DefaultBranch     sql.NullString `json:"default_branch"`
	LocalExecBranch   sql.NullString `json:"local_exec_branch"`
	RemoteMergeBranch sql.NullString `json:"remote_merge_branch"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Color,
		arg.Location,
		arg.DefaultBranch,
		arg.LocalExecBranch,
		arg.RemoteMergeBranch,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Location,
		&i.DefaultBranch,
		&i.LocalExecBranch,
		&i.RemoteMergeBranch,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, status, color, created_at, updated_at, location, default_branch, local_exec_branch, remote_merge_branch FROM projects WHERE id = ? LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Location,
		&i.DefaultBranch,
		&i.LocalExecBranch,
		&i.RemoteMergeBranch,
	)
	return i, err
}

const getProjectDoneTaskCount = `-- name: GetProjectDoneTaskCount :one
SELECT COUNT(*) as count FROM tasks WHERE project_id = ? AND status = 'done'
`

func (q *Queries) GetProjectDoneTaskCount(ctx context.Context, projectID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProjectDoneTaskCount, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProjectTaskCount = `-- name: GetProjectTaskCount :one
SELECT COUNT(*) as count FROM tasks WHERE project_id = ?
`

func (q *Queries) GetProjectTaskCount(ctx context.Context, projectID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProjectTaskCount, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, description, status, color, created_at, updated_at, location, default_branch, local_exec_branch, remote_merge_branch FROM projects ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Location,
			&i.DefaultBranch,
			&i.LocalExecBranch,
			&i.RemoteMergeBranch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByStatus = `-- name: ListProjectsByStatus :many
SELECT id, name, description, status, color, created_at, updated_at, location, default_branch, local_exec_branch, remote_merge_branch FROM projects WHERE status = ? ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByStatus(ctx context.Context, status sql.NullString) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Location,
			&i.DefaultBranch,
			&i.LocalExecBranch,
			&i.RemoteMergeBranch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
    name = ?, 
    description = ?, 
    status = ?, 
    color = ?,
    location = ?,
    default_branch = ?,
    local_exec_branch = ?,
    remote_merge_branch = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? 
RETURNING id, name, description, status, color, created_at, updated_at, location, default_branch, local_exec_branch, remote_merge_branch
`

type UpdateProjectParams struct {
	Name              string         `json:"name"`
	Description       sql.NullString `json:"description"`
	Status            sql.NullString `json:"status"`
	Color             sql.NullString `json:"color"`
	Location          sql.NullString `json:"location"`
	DefaultBranch     sql.NullString `json:"default_branch"`
	LocalExecBranch   sql.NullString `json:"local_exec_branch"`
	RemoteMergeBranch sql.NullString `json:"remote_merge_branch"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Color,
		arg.Location,
		arg.DefaultBranch,
		arg.LocalExecBranch,
		arg.RemoteMergeBranch,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Location,
		&i.DefaultBranch,
		&i.LocalExecBranch,
		&i.RemoteMergeBranch,
	)
	return i, err
}
