// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"
	"database/sql"
)

const getSettings = `-- name: GetSettings :one
SELECT id, openclaw_gateway_url, openclaw_gateway_token, default_model, max_parallel_executions, default_project_directory, gsd_depth, gsd_mode, gsd_research_enabled, gsd_plan_check_enabled, gsd_verifier_enabled, ralph_max_iterations, ralph_auto_commit, theme, updated_at FROM settings WHERE id = 'default' LIMIT 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.OpenclawGatewayUrl,
		&i.OpenclawGatewayToken,
		&i.DefaultModel,
		&i.MaxParallelExecutions,
		&i.DefaultProjectDirectory,
		&i.GsdDepth,
		&i.GsdMode,
		&i.GsdResearchEnabled,
		&i.GsdPlanCheckEnabled,
		&i.GsdVerifierEnabled,
		&i.RalphMaxIterations,
		&i.RalphAutoCommit,
		&i.Theme,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings SET
    openclaw_gateway_url = ?, openclaw_gateway_token = ?,
    default_model = ?, max_parallel_executions = ?,
    default_project_directory = ?,
    gsd_depth = ?, gsd_mode = ?, gsd_research_enabled = ?, gsd_plan_check_enabled = ?, gsd_verifier_enabled = ?,
    ralph_max_iterations = ?, ralph_auto_commit = ?, theme = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = 'default' RETURNING id, openclaw_gateway_url, openclaw_gateway_token, default_model, max_parallel_executions, default_project_directory, gsd_depth, gsd_mode, gsd_research_enabled, gsd_plan_check_enabled, gsd_verifier_enabled, ralph_max_iterations, ralph_auto_commit, theme, updated_at
`

type UpdateSettingsParams struct {
	OpenclawGatewayUrl      sql.NullString `json:"openclaw_gateway_url"`
	OpenclawGatewayToken    sql.NullString `json:"openclaw_gateway_token"`
	DefaultModel            sql.NullString `json:"default_model"`
	MaxParallelExecutions   sql.NullInt64  `json:"max_parallel_executions"`
	DefaultProjectDirectory sql.NullString `json:"default_project_directory"`
	GsdDepth                sql.NullString `json:"gsd_depth"`
	GsdMode                 sql.NullString `json:"gsd_mode"`
	GsdResearchEnabled      sql.NullInt64  `json:"gsd_research_enabled"`
	GsdPlanCheckEnabled     sql.NullInt64  `json:"gsd_plan_check_enabled"`
	GsdVerifierEnabled      sql.NullInt64  `json:"gsd_verifier_enabled"`
	RalphMaxIterations      sql.NullInt64  `json:"ralph_max_iterations"`
	RalphAutoCommit         sql.NullInt64  `json:"ralph_auto_commit"`
	Theme                   sql.NullString `json:"theme"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, updateSettings,
		arg.OpenclawGatewayUrl,
		arg.OpenclawGatewayToken,
		arg.DefaultModel,
		arg.MaxParallelExecutions,
		arg.DefaultProjectDirectory,
		arg.GsdDepth,
		arg.GsdMode,
		arg.GsdResearchEnabled,
		arg.GsdPlanCheckEnabled,
		arg.GsdVerifierEnabled,
		arg.RalphMaxIterations,
		arg.RalphAutoCommit,
		arg.Theme,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.OpenclawGatewayUrl,
		&i.OpenclawGatewayToken,
		&i.DefaultModel,
		&i.MaxParallelExecutions,
		&i.DefaultProjectDirectory,
		&i.GsdDepth,
		&i.GsdMode,
		&i.GsdResearchEnabled,
		&i.GsdPlanCheckEnabled,
		&i.GsdVerifierEnabled,
		&i.RalphMaxIterations,
		&i.RalphAutoCommit,
		&i.Theme,
		&i.UpdatedAt,
	)
	return i, err
}
