// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sub_agents.sql

package db

import (
	"context"
	"database/sql"
)

const createSubAgent = `-- name: CreateSubAgent :one
INSERT INTO sub_agents (id, orchestrator_id, task_id, name, status, session_key, session_label, purpose, iteration)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, orchestrator_id, task_id, name, status, session_key, session_label, purpose, iteration, output, error, spawned_at, completed_at
`

type CreateSubAgentParams struct {
	ID             string         `json:"id"`
	OrchestratorID string         `json:"orchestrator_id"`
	TaskID         sql.NullString `json:"task_id"`
	Name           string         `json:"name"`
	Status         sql.NullString `json:"status"`
	SessionKey     sql.NullString `json:"session_key"`
	SessionLabel   sql.NullString `json:"session_label"`
	Purpose        sql.NullString `json:"purpose"`
	Iteration      sql.NullInt64  `json:"iteration"`
}

func (q *Queries) CreateSubAgent(ctx context.Context, arg CreateSubAgentParams) (SubAgent, error) {
	row := q.db.QueryRowContext(ctx, createSubAgent,
		arg.ID,
		arg.OrchestratorID,
		arg.TaskID,
		arg.Name,
		arg.Status,
		arg.SessionKey,
		arg.SessionLabel,
		arg.Purpose,
		arg.Iteration,
	)
	var i SubAgent
	err := row.Scan(
		&i.ID,
		&i.OrchestratorID,
		&i.TaskID,
		&i.Name,
		&i.Status,
		&i.SessionKey,
		&i.SessionLabel,
		&i.Purpose,
		&i.Iteration,
		&i.Output,
		&i.Error,
		&i.SpawnedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteSubAgent = `-- name: DeleteSubAgent :exec
DELETE FROM sub_agents WHERE id = ?
`

func (q *Queries) DeleteSubAgent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSubAgent, id)
	return err
}

const getSubAgent = `-- name: GetSubAgent :one
SELECT id, orchestrator_id, task_id, name, status, session_key, session_label, purpose, iteration, output, error, spawned_at, completed_at FROM sub_agents WHERE id = ? LIMIT 1
`

func (q *Queries) GetSubAgent(ctx context.Context, id string) (SubAgent, error) {
	row := q.db.QueryRowContext(ctx, getSubAgent, id)
	var i SubAgent
	err := row.Scan(
		&i.ID,
		&i.OrchestratorID,
		&i.TaskID,
		&i.Name,
		&i.Status,
		&i.SessionKey,
		&i.SessionLabel,
		&i.Purpose,
		&i.Iteration,
		&i.Output,
		&i.Error,
		&i.SpawnedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listSubAgentsByOrchestrator = `-- name: ListSubAgentsByOrchestrator :many
SELECT id, orchestrator_id, task_id, name, status, session_key, session_label, purpose, iteration, output, error, spawned_at, completed_at FROM sub_agents WHERE orchestrator_id = ? ORDER BY spawned_at DESC
`

func (q *Queries) ListSubAgentsByOrchestrator(ctx context.Context, orchestratorID string) ([]SubAgent, error) {
	rows, err := q.db.QueryContext(ctx, listSubAgentsByOrchestrator, orchestratorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubAgent{}
	for rows.Next() {
		var i SubAgent
		if err := rows.Scan(
			&i.ID,
			&i.OrchestratorID,
			&i.TaskID,
			&i.Name,
			&i.Status,
			&i.SessionKey,
			&i.SessionLabel,
			&i.Purpose,
			&i.Iteration,
			&i.Output,
			&i.Error,
			&i.SpawnedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubAgentsByTask = `-- name: ListSubAgentsByTask :many
SELECT id, orchestrator_id, task_id, name, status, session_key, session_label, purpose, iteration, output, error, spawned_at, completed_at FROM sub_agents WHERE task_id = ? ORDER BY spawned_at DESC
`

func (q *Queries) ListSubAgentsByTask(ctx context.Context, taskID sql.NullString) ([]SubAgent, error) {
	rows, err := q.db.QueryContext(ctx, listSubAgentsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubAgent{}
	for rows.Next() {
		var i SubAgent
		if err := rows.Scan(
			&i.ID,
			&i.OrchestratorID,
			&i.TaskID,
			&i.Name,
			&i.Status,
			&i.SessionKey,
			&i.SessionLabel,
			&i.Purpose,
			&i.Iteration,
			&i.Output,
			&i.Error,
			&i.SpawnedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubAgentStatus = `-- name: UpdateSubAgentStatus :exec
UPDATE sub_agents SET status = ?, output = ?, error = ?, completed_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateSubAgentStatusParams struct {
	Status sql.NullString `json:"status"`
	Output sql.NullString `json:"output"`
	Error  sql.NullString `json:"error"`
	ID     string         `json:"id"`
}

func (q *Queries) UpdateSubAgentStatus(ctx context.Context, arg UpdateSubAgentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSubAgentStatus,
		arg.Status,
		arg.Output,
		arg.Error,
		arg.ID,
	)
	return err
}
